import { ProductWithImages } from "./products";

export interface FallbackProductDetail extends ProductWithImages {
  variants: Array<{
    id: string;
    productId: string;
    size: string;
    stock: number;
    sku: string;
    price: number;
    salePrice: number | null;
  }>;
  categoryRel: { id: string; name: string; slug: string } | null;
  reviews: Array<{
    id: string;
    displayName: string;
    rating: number;
    reviewText: string;
    customerPhotoUrl: string | null;
    productPhotoUrl: string | null;
    createdAt: Date;
  }>;
}

export const FALLBACK_PRODUCTS: FallbackProductDetail[] = [
  {
    id: "prod-apex-runner-x1",
    name: "Apex Runner X1",
    slug: "apex-runner-x1",
    sku: "KNOOS-ARX1-M-BLK",
    gender: "MEN",
    category: "Sneakers",
    categoryId: "cat-sneakers",
    color: "Stealth Black",
    colorGroupKey: "apex-runner-x1-group",
    subCategory: "Running",
    upperMaterial: "Engineered Breathable Mesh",
    innerMaterial: "Memory Foam Collar",
    sole: "High-Rebound EVA & Carbon Rubber",
    price: 2999,
    salePrice: 2499,
    costPrice: null,
    hsnCode: "640411",
    gstPercentage: 18,
    packagingLength: 32,
    packagingBreadth: 20,
    packagingHeight: 12,
    packagingWeight: 0.85,
    attributes: null,
    status: "ACTIVE",
    createdAt: new Date("2026-09-01T00:00:00.000Z"),
    updatedAt: new Date("2026-09-20T00:00:00.000Z"),
    images: [
      { id: "img-arx1-1", productId: "prod-apex-runner-x1", imageUrl: "/images/men-category.jpg", isVideo: false, sortOrder: 0 },
      { id: "img-arx1-2", productId: "prod-apex-runner-x1", imageUrl: "/images/process-footwear.jpg", isVideo: false, sortOrder: 1 },
      { id: "img-arx1-3", productId: "prod-apex-runner-x1", imageUrl: "/images/hero-poster.webp", isVideo: false, sortOrder: 2 },
    ],
    variants: [
      { id: "var-arx1-7", productId: "prod-apex-runner-x1", size: "7", stock: 12, sku: "KNOOS-ARX1-M-BLK-07", price: 2999, salePrice: 2499 },
      { id: "var-arx1-8", productId: "prod-apex-runner-x1", size: "8", stock: 24, sku: "KNOOS-ARX1-M-BLK-08", price: 2999, salePrice: 2499 },
      { id: "var-arx1-9", productId: "prod-apex-runner-x1", size: "9", stock: 18, sku: "KNOOS-ARX1-M-BLK-09", price: 2999, salePrice: 2499 },
      { id: "var-arx1-10", productId: "prod-apex-runner-x1", size: "10", stock: 15, sku: "KNOOS-ARX1-M-BLK-10", price: 2999, salePrice: 2499 },
      { id: "var-arx1-11", productId: "prod-apex-runner-x1", size: "11", stock: 6, sku: "KNOOS-ARX1-M-BLK-11", price: 2999, salePrice: 2499 },
    ],
    categoryRel: { id: "cat-sneakers", name: "Sneakers", slug: "sneakers" },
    reviews: [
      {
        id: "rev-1",
        displayName: "Aarav Sharma",
        rating: 5,
        reviewText: "The cushioning and lightweight build are unmatched for all-day commutes. Truly premium feel.",
        customerPhotoUrl: null,
        productPhotoUrl: null,
        createdAt: new Date("2026-09-15T00:00:00.000Z"),
      },
      {
        id: "rev-2",
        displayName: "Vikram Malhotra",
        rating: 5,
        reviewText: "Clean lines and understated branding. Fits true to size with exceptional arch support.",
        customerPhotoUrl: null,
        productPhotoUrl: null,
        createdAt: new Date("2026-09-18T00:00:00.000Z"),
      },
    ],
    description:
      "Engineered for fluid everyday movement. The Apex Runner X1 combines lightweight breathable knit with responsive multi-density cushioning for effortless all-day comfort.",
  },
  {
    id: "prod-luna-court-classic",
    name: "Luna Court Classic",
    slug: "luna-court-classic",
    sku: "KNOOS-LCC-W-WHT",
    gender: "WOMEN",
    category: "Sneakers",
    categoryId: "cat-sneakers",
    color: "Chalk White",
    colorGroupKey: "luna-court-group",
    subCategory: "Casual",
    upperMaterial: "Full-Grain Italian Calfskin",
    innerMaterial: "Supple Leather Lining",
    sole: "Durable Cupsole Rubber",
    price: 3499,
    salePrice: 2999,
    costPrice: null,
    hsnCode: "640411",
    gstPercentage: 18,
    packagingLength: 30,
    packagingBreadth: 18,
    packagingHeight: 11,
    packagingWeight: 0.78,
    attributes: null,
    status: "ACTIVE",
    createdAt: new Date("2026-09-02T00:00:00.000Z"),
    updatedAt: new Date("2026-09-21T00:00:00.000Z"),
    images: [
      { id: "img-lcc-1", productId: "prod-luna-court-classic", imageUrl: "/images/women-category.jpg", isVideo: false, sortOrder: 0 },
      { id: "img-lcc-2", productId: "prod-luna-court-classic", imageUrl: "/images/process-footwear.jpg", isVideo: false, sortOrder: 1 },
    ],
    variants: [
      { id: "var-lcc-5", productId: "prod-luna-court-classic", size: "5", stock: 10, sku: "KNOOS-LCC-W-WHT-05", price: 3499, salePrice: 2999 },
      { id: "var-lcc-6", productId: "prod-luna-court-classic", size: "6", stock: 20, sku: "KNOOS-LCC-W-WHT-06", price: 3499, salePrice: 2999 },
      { id: "var-lcc-7", productId: "prod-luna-court-classic", size: "7", stock: 15, sku: "KNOOS-LCC-W-WHT-07", price: 3499, salePrice: 2999 },
      { id: "var-lcc-8", productId: "prod-luna-court-classic", size: "8", stock: 8, sku: "KNOOS-LCC-W-WHT-08", price: 3499, salePrice: 2999 },
    ],
    categoryRel: { id: "cat-sneakers", name: "Sneakers", slug: "sneakers" },
    reviews: [
      {
        id: "rev-3",
        displayName: "Ananya Iyer",
        rating: 5,
        reviewText: "Minimalist, chic, and goes with everything in my wardrobe. Soft leather right out of the box.",
        customerPhotoUrl: null,
        productPhotoUrl: null,
        createdAt: new Date("2026-09-19T00:00:00.000Z"),
      },
    ],
    description:
      "A timeless court silhouette crafted in soft full-grain leather. Finished with cushioned footbeds for effortless transitions from brunch to late evenings.",
  },
  {
    id: "prod-knoos-chelsea-noir",
    name: "KNOOS Chelsea Noir",
    slug: "knoos-chelsea-noir",
    sku: "KNOOS-CHL-M-BLK",
    gender: "MEN",
    category: "Boots",
    categoryId: "cat-boots",
    color: "Midnight Black",
    colorGroupKey: "chelsea-noir-group",
    subCategory: "Boots",
    upperMaterial: "Water-Resistant Oiled Nubuck",
    innerMaterial: "Microfiber Suede",
    sole: "Lugged Commando Sole",
    price: 4999,
    salePrice: 4299,
    costPrice: null,
    hsnCode: "640351",
    gstPercentage: 18,
    packagingLength: 34,
    packagingBreadth: 22,
    packagingHeight: 14,
    packagingWeight: 1.1,
    attributes: null,
    status: "ACTIVE",
    createdAt: new Date("2026-09-03T00:00:00.000Z"),
    updatedAt: new Date("2026-09-22T00:00:00.000Z"),
    images: [
      { id: "img-chl-1", productId: "prod-knoos-chelsea-noir", imageUrl: "/images/process-footwear.jpg", isVideo: false, sortOrder: 0 },
      { id: "img-chl-2", productId: "prod-knoos-chelsea-noir", imageUrl: "/images/men-category.jpg", isVideo: false, sortOrder: 1 },
    ],
    variants: [
      { id: "var-chl-8", productId: "prod-knoos-chelsea-noir", size: "8", stock: 14, sku: "KNOOS-CHL-M-BLK-08", price: 4999, salePrice: 4299 },
      { id: "var-chl-9", productId: "prod-knoos-chelsea-noir", size: "9", stock: 18, sku: "KNOOS-CHL-M-BLK-09", price: 4999, salePrice: 4299 },
      { id: "var-chl-10", productId: "prod-knoos-chelsea-noir", size: "10", stock: 12, sku: "KNOOS-CHL-M-BLK-10", price: 4999, salePrice: 4299 },
    ],
    categoryRel: { id: "cat-boots", name: "Boots", slug: "boots" },
    reviews: [
      {
        id: "rev-4",
        displayName: "Rohan Kapoor",
        rating: 5,
        reviewText: "Stunning silhouette and incredible leather quality. Rugged yet formal enough for tailored trousers.",
        customerPhotoUrl: null,
        productPhotoUrl: null,
        createdAt: new Date("2026-09-17T00:00:00.000Z"),
      },
    ],
    description:
      "Constructed with oil-tanned nubuck and stretch side gussets. A classic silhouette re-engineered with modern shock-absorbing insoles.",
  },
  {
    id: "prod-velox-knit-trainer",
    name: "Velox Knit Trainer",
    slug: "velox-knit-trainer",
    sku: "KNOOS-VLX-M-GRY",
    gender: "MEN",
    category: "Casual",
    categoryId: "cat-casual",
    color: "Heather Slate",
    colorGroupKey: "velox-group",
    subCategory: "Sneakers",
    upperMaterial: "Seamless Engineered Knit",
    innerMaterial: "Breathable Textile",
    sole: "Ultralight Phylon Sole",
    price: 2799,
    salePrice: 2199,
    costPrice: null,
    hsnCode: "640411",
    gstPercentage: 18,
    packagingLength: 31,
    packagingBreadth: 19,
    packagingHeight: 12,
    packagingWeight: 0.72,
    attributes: null,
    status: "ACTIVE",
    createdAt: new Date("2026-09-04T00:00:00.000Z"),
    updatedAt: new Date("2026-09-22T00:00:00.000Z"),
    images: [
      { id: "img-vlx-1", productId: "prod-velox-knit-trainer", imageUrl: "/images/hero-poster.webp", isVideo: false, sortOrder: 0 },
      { id: "img-vlx-2", productId: "prod-velox-knit-trainer", imageUrl: "/images/men-category.jpg", isVideo: false, sortOrder: 1 },
    ],
    variants: [
      { id: "var-vlx-8", productId: "prod-velox-knit-trainer", size: "8", stock: 15, sku: "KNOOS-VLX-M-GRY-08", price: 2799, salePrice: 2199 },
      { id: "var-vlx-9", productId: "prod-velox-knit-trainer", size: "9", stock: 22, sku: "KNOOS-VLX-M-GRY-09", price: 2799, salePrice: 2199 },
      { id: "var-vlx-10", productId: "prod-velox-knit-trainer", size: "10", stock: 16, sku: "KNOOS-VLX-M-GRY-10", price: 2799, salePrice: 2199 },
    ],
    categoryRel: { id: "cat-casual", name: "Casual", slug: "casual" },
    reviews: [],
    description:
      "Seamless 3D knit upper contours to the foot with natural flexibility. Built for quick strides and effortless daily wear.",
  },
  {
    id: "prod-aura-leather-loafer",
    name: "Aura Leather Loafer",
    slug: "aura-leather-loafer",
    sku: "KNOOS-AUR-W-COG",
    gender: "WOMEN",
    category: "Loafers",
    categoryId: "cat-loafers",
    color: "Warm Cognac",
    colorGroupKey: "aura-loafer-group",
    subCategory: "Loafers",
    upperMaterial: "Hand-Burnished Calfskin",
    innerMaterial: "Soft Lambskin",
    sole: "Stacked Heel Leather Sole with Rubber Inset",
    price: 3899,
    salePrice: 3299,
    costPrice: null,
    hsnCode: "640359",
    gstPercentage: 18,
    packagingLength: 30,
    packagingBreadth: 18,
    packagingHeight: 11,
    packagingWeight: 0.75,
    attributes: null,
    status: "ACTIVE",
    createdAt: new Date("2026-09-05T00:00:00.000Z"),
    updatedAt: new Date("2026-09-23T00:00:00.000Z"),
    images: [
      { id: "img-aur-1", productId: "prod-aura-leather-loafer", imageUrl: "/images/women-category.jpg", isVideo: false, sortOrder: 0 },
      { id: "img-aur-2", productId: "prod-aura-leather-loafer", imageUrl: "/images/process-footwear.jpg", isVideo: false, sortOrder: 1 },
    ],
    variants: [
      { id: "var-aur-6", productId: "prod-aura-leather-loafer", size: "6", stock: 12, sku: "KNOOS-AUR-W-COG-06", price: 3899, salePrice: 3299 },
      { id: "var-aur-7", productId: "prod-aura-leather-loafer", size: "7", stock: 18, sku: "KNOOS-AUR-W-COG-07", price: 3899, salePrice: 3299 },
      { id: "var-aur-8", productId: "prod-aura-leather-loafer", size: "8", stock: 10, sku: "KNOOS-AUR-W-COG-08", price: 3899, salePrice: 3299 },
    ],
    categoryRel: { id: "cat-loafers", name: "Loafers", slug: "loafers" },
    reviews: [],
    description:
      "Sculpted penny loafer crafted with burnished full-grain leather. Finished with padded arch support and refined tonal stitching.",
  },
  {
    id: "prod-trail-blazer-pro",
    name: "Trail Blazer Pro",
    slug: "trail-blazer-pro",
    sku: "KNOOS-TBP-M-OLV",
    gender: "MEN",
    category: "Outdoor",
    categoryId: "cat-outdoor",
    color: "Olive Field",
    colorGroupKey: "trail-blazer-group",
    subCategory: "Outdoor",
    upperMaterial: "Ripstop Ballistic Mesh & Suede",
    innerMaterial: "Waterproof Membrane",
    sole: "Vibram-Grade Traction Tread",
    price: 4299,
    salePrice: 3699,
    costPrice: null,
    hsnCode: "640391",
    gstPercentage: 18,
    packagingLength: 33,
    packagingBreadth: 21,
    packagingHeight: 13,
    packagingWeight: 0.95,
    attributes: null,
    status: "ACTIVE",
    createdAt: new Date("2026-09-06T00:00:00.000Z"),
    updatedAt: new Date("2026-09-24T00:00:00.000Z"),
    images: [
      { id: "img-tbp-1", productId: "prod-trail-blazer-pro", imageUrl: "/images/process-footwear.jpg", isVideo: false, sortOrder: 0 },
      { id: "img-tbp-2", productId: "prod-trail-blazer-pro", imageUrl: "/images/men-category.jpg", isVideo: false, sortOrder: 1 },
    ],
    variants: [
      { id: "var-tbp-8", productId: "prod-trail-blazer-pro", size: "8", stock: 8, sku: "KNOOS-TBP-M-OLV-08", price: 4299, salePrice: 3699 },
      { id: "var-tbp-9", productId: "prod-trail-blazer-pro", size: "9", stock: 14, sku: "KNOOS-TBP-M-OLV-09", price: 4299, salePrice: 3699 },
      { id: "var-tbp-10", productId: "prod-trail-blazer-pro", size: "10", stock: 11, sku: "KNOOS-TBP-M-OLV-10", price: 4299, salePrice: 3699 },
    ],
    categoryRel: { id: "cat-outdoor", name: "Outdoor", slug: "outdoor" },
    reviews: [],
    description:
      "All-weather durability with rugged grip and waterproof lining. Built to transition seamlessly from trail excursions to city pavement.",
  },
];
